# Generated by Django 3.0.7 on 2020-06-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duvidas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Duvidas',
            new_name='Duvida',
        ),
    ]
